#ifndef _TELEPORT_CONFIG_H_
#define _TELEPORT_CONFIG_H_

#undef TELEPORT_COMPRESSION
#define TELEPORT_COMPRESSION_EMBEDDED

#undef TELEPORT_PRINTING
#define TELEPORT_COHERENCE_HISTORY_LENGTH 10
#define TELEPORT_ACCESS_TABLE_LENGTH 1000

#define TELEPORT_PARALLELISM 1
#define TELEPORT_MAX_CONCURRENCY 8

#endif